workspace(name = "tf-serving-client-test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TensorFlow Serving Dependencies
# https://github.com/tensorflow/serving/blob/2.6.2/WORKSPACE
http_archive(
    name = "com_github_tensorflow_serving",
    sha256 = "193d2cf959d9444a2837fe13f3efa51127532ad9ee99585903301c1a4a4c21c9",
    strip_prefix = "serving-2.6.2",
    url = "https://github.com/tensorflow/serving/archive/2.6.2.tar.gz",
)

load("@com_github_tensorflow_serving//tensorflow_serving:repo.bzl", "tensorflow_http_archive")

tensorflow_http_archive(
    name = "org_tensorflow",
    git_commit = "c2363d6d025981c661f8cbecf4c73ca7fbf38caf",
    sha256 = "add5982a3ce3b9964b7122dd0d28927b6a9d9abd8f95a89eda18ca76648a0ae8",
)

load("@com_github_tensorflow_serving//tensorflow_serving:workspace.bzl", "tf_serving_workspace")

tf_serving_workspace()

load("@org_tensorflow//tensorflow:workspace3.bzl", "workspace")

workspace()

load("@org_tensorflow//tensorflow:workspace2.bzl", "workspace")

workspace()

load("@org_tensorflow//tensorflow:workspace1.bzl", "workspace")

workspace()

load("@org_tensorflow//tensorflow:workspace0.bzl", "workspace")

workspace()

http_archive(
    name = "com_github_bazelbuild_buildtools",
    sha256 = "ae34c344514e08c23e90da0e2d6cb700fcd28e80c02e23e4d5715dddcb42f7b3",
    strip_prefix = "buildtools-4.2.2",
    urls = [
        "https://github.com/bazelbuild/buildtools/archive/refs/tags/4.2.2.tar.gz",
    ],
)
